# Transit Ridership Optimizer - Exploratory Data Analysis

This notebook explores the Calgary Transit Ridership and Stops datasets to understand
patterns, distributions, and network structure for forecasting and optimization.

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import seaborn as sns
import matplotlib.pyplot as plt
import sys
sys.path.insert(0, '..')
from src.data_loader import (
    load_or_fetch_ridership, load_or_fetch_stops,
    preprocess_ridership, preprocess_stops, engineer_features,
)

pd.set_option('display.max_columns', 50)
pd.set_option('display.float_format', lambda x: f'{x:,.2f}')

## 1. Load Data

In [2]:
df_ridership_raw = load_or_fetch_ridership('../data', limit=100000)
print(f'Raw ridership shape: {df_ridership_raw.shape}')
df_ridership_raw.head()

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

Raw ridership shape: (0, 0)

Empty DataFrame
Columns: []
Index: []

In [3]:
df_stops_raw = load_or_fetch_stops('../data', limit=10000)
print(f'Raw stops shape: {df_stops_raw.shape}')
df_stops_raw.head()

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

Raw stops shape: (7707, 11)

,teleride_number,stop_name,status,create_dt_utc,mod_dt_utc,globalid,point,:@computed_region_4b54_tmc4,:@computed_region_kxmf_bzkv,:@computed_region_4a3i_ccfj,:@computed_region_p8tp_5dkv
0,7347,EB 37 AV NE @ 27 ST NE,ACTIVE,2025-12-11T17:40:08.000Z,2025-12-11T17:40:08.000Z,db23235c-6268-4188-8123-268820023a16,"{'type': 'Point', 'coordinates': [-113.9941364...",9,71,4,3
1,7354,NB 19 ST NE @ 41 AV NE,ACTIVE,2025-12-11T17:40:08.000Z,2025-12-11T17:40:08.000Z,47294484-1286-45a1-a575-fd0186e4f33e,"{'type': 'Point', 'coordinates': [-114.0114369...",9,72,4,3
2,4498,EB Temple DR @ 56 ST NE,ACTIVE,2025-12-11T17:40:08.000Z,2025-12-11T17:40:08.000Z,2ccdcc0f-58ec-4412-98ad-8158d0016580,"{'type': 'Point', 'coordinates': [-113.9516751...",9,22,4,3
3,8148,NB 52 ST NE @ 26 AV NE,INACTIVE,2025-12-11T17:40:08.000Z,2025-12-11T17:40:08.000Z,f1fc08ba-db01-4101-93ae-1f5812e1627e,"{'type': 'Point', 'coordinates': [-113.9582629...",9,36,4,3
4,1989,WB 80 AV NE @ Saddlestone GV NE,ACTIVE,2025-12-11T17:40:08.000Z,2025-12-11T17:40:08.000Z,992b4967-bff8-4fab-a22e-2d8dbd9b6ac7,"{'type': 'Point', 'coordinates': [-113.9254041...",11,2,4,1

In [4]:
df_ridership_raw.info()
print('---')
df_stops_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7707 entries, 0 to 7706
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   teleride_number              7707 non-null   object
 1   stop_name                    7707 non-null   object
 2   status                       7707 non-null   object
 3   create_dt_utc                7707 non-null   object
 4   mod_dt_utc                   7707 non-null   object
 5   globalid                     7707 non-null   object
 6   point                        7707 non-null   object
 7   :@computed_region_4b54_tmc4  7692 non-null   object
 8   :@computed_region_kxmf_bzkv  7692 non-null   object
 9   :@computed_region_4a3i_ccfj  7692 non-null   object
 10  :@computed_region_p8tp_5dkv  7692 non-null   object
dtypes: object(11)
memory usage: 662.4+ KB

## 2. Data Quality Assessment

In [5]:
# Missing values - ridership
missing_r = df_ridership_raw.isnull().sum()
missing_r_pct = (missing_r / len(df_ridership_raw) * 100).round(2)
missing_r_df = pd.DataFrame({'Missing': missing_r, 'Percent': missing_r_pct})
print('Ridership missing values:')
print(missing_r_df[missing_r_df['Missing'] > 0].sort_values('Percent', ascending=False))

print('\n---\n')

# Missing values - stops
missing_s = df_stops_raw.isnull().sum()
missing_s_pct = (missing_s / len(df_stops_raw) * 100).round(2)
missing_s_df = pd.DataFrame({'Missing': missing_s, 'Percent': missing_s_pct})
print('Stops missing values:')
print(missing_s_df[missing_s_df['Missing'] > 0].sort_values('Percent', ascending=False))

Ridership missing values:
Empty DataFrame
Columns: [Missing, Percent]
Index: []

---

Stops missing values:

                             Missing  Percent
:@computed_region_4b54_tmc4       15     0.19
:@computed_region_kxmf_bzkv       15     0.19
:@computed_region_4a3i_ccfj       15     0.19
:@computed_region_p8tp_5dkv       15     0.19

## 3. Preprocess & Engineer Features

In [6]:
df = preprocess_ridership(df_ridership_raw)
df = engineer_features(df)
print(f'Processed ridership shape: {df.shape}')
df.head()

Processed ridership shape: (0, 0)

Empty DataFrame
Columns: []
Index: []

In [7]:
stops = preprocess_stops(df_stops_raw)
print(f'Processed stops shape: {stops.shape}')
stops.head()

Processed stops shape: (7707, 11)

,teleride_number,stop_name,status,create_dt_utc,mod_dt_utc,globalid,point,:@computed_region_4b54_tmc4,:@computed_region_kxmf_bzkv,:@computed_region_4a3i_ccfj,:@computed_region_p8tp_5dkv
0,7347,EB 37 AV NE @ 27 ST NE,ACTIVE,2025-12-11T17:40:08.000Z,2025-12-11T17:40:08.000Z,db23235c-6268-4188-8123-268820023a16,"{'type': 'Point', 'coordinates': [-113.9941364...",9,71,4,3
1,7354,NB 19 ST NE @ 41 AV NE,ACTIVE,2025-12-11T17:40:08.000Z,2025-12-11T17:40:08.000Z,47294484-1286-45a1-a575-fd0186e4f33e,"{'type': 'Point', 'coordinates': [-114.0114369...",9,72,4,3
2,4498,EB Temple DR @ 56 ST NE,ACTIVE,2025-12-11T17:40:08.000Z,2025-12-11T17:40:08.000Z,2ccdcc0f-58ec-4412-98ad-8158d0016580,"{'type': 'Point', 'coordinates': [-113.9516751...",9,22,4,3
3,8148,NB 52 ST NE @ 26 AV NE,INACTIVE,2025-12-11T17:40:08.000Z,2025-12-11T17:40:08.000Z,f1fc08ba-db01-4101-93ae-1f5812e1627e,"{'type': 'Point', 'coordinates': [-113.9582629...",9,36,4,3
4,1989,WB 80 AV NE @ Saddlestone GV NE,ACTIVE,2025-12-11T17:40:08.000Z,2025-12-11T17:40:08.000Z,992b4967-bff8-4fab-a22e-2d8dbd9b6ac7,"{'type': 'Point', 'coordinates': [-113.9254041...",11,2,4,1

## 4. Target Variable Analysis (Ridership Trends)

In [8]:
if 'ridership' in df.columns and 'date' in df.columns:
    fig = px.line(df, x='date', y='ridership',
                  title='Monthly Transit Ridership Over Time',
                  labels={'date': 'Date', 'ridership': 'Ridership'})
    fig.update_layout(height=450)
    fig.show()

    print('Ridership Statistics:')
    print(df['ridership'].describe())

## 5. Categorical / Group Breakdown

In [9]:
# Check for ridership breakdown columns
non_meta_cols = [c for c in df.columns if c not in ['date', 'year', 'month', 'quarter',
                 'ridership', 'lag_1m', 'lag_3m', 'lag_12m',
                 'rolling_mean_3m', 'rolling_mean_6m', 'rolling_mean_12m', 'yoy_change']]
print(f'Other columns in ridership data: {non_meta_cols}')

# If route breakdown exists
if 'route_name' in stops.columns:
    route_counts = stops['route_name'].value_counts().head(20)
    fig = px.bar(x=route_counts.index, y=route_counts.values,
                 title='Top 20 Routes by Stop Count',
                 labels={'x': 'Route', 'y': 'Stop Count'})
    fig.update_layout(height=400)
    fig.show()

Other columns in ridership data: []

## 6. Temporal / Seasonal Patterns

In [10]:
if 'month' in df.columns and 'ridership' in df.columns:
    month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                   'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    monthly = df.groupby('month')['ridership'].mean().reset_index()
    monthly['Month Name'] = monthly['month'].map(lambda x: month_names[int(x)-1] if 1 <= x <= 12 else 'Unk')

    fig = px.bar(monthly, x='Month Name', y='ridership',
                 title='Average Ridership by Month (Seasonal Pattern)',
                 color='ridership', color_continuous_scale='Viridis')
    fig.update_layout(height=400, showlegend=False)
    fig.show()

if 'year' in df.columns and 'ridership' in df.columns:
    yearly = df.groupby('year')['ridership'].sum().reset_index()
    fig = px.bar(yearly, x='year', y='ridership',
                 title='Annual Total Ridership',
                 color='ridership', color_continuous_scale='Blues')
    fig.update_layout(height=400, showlegend=False)
    fig.show()

## 7. Network Structure Analysis

In [11]:
if 'latitude' in stops.columns and 'longitude' in stops.columns:
    fig = px.scatter_mapbox(stops.dropna(subset=['latitude', 'longitude']),
                            lat='latitude', lon='longitude',
                            mapbox_style='carto-positron', zoom=10,
                            title='Calgary Transit Stop Locations')
    fig.update_layout(height=600)
    fig.show()

print(f'Total stops: {len(stops)}')
if 'route_name' in stops.columns:
    print(f'Unique routes: {stops["route_name"].nunique()}')

Total stops: 7707

## 8. Correlation Analysis

In [12]:
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
if 'ridership' in numeric_cols and len(numeric_cols) > 1:
    key_numeric = [c for c in ['ridership', 'lag_1m', 'lag_3m', 'lag_12m',
                   'rolling_mean_3m', 'rolling_mean_6m', 'rolling_mean_12m',
                   'yoy_change', 'month', 'year']
                   if c in df.columns]
    if len(key_numeric) > 1:
        corr = df[key_numeric].corr()
        fig = px.imshow(corr, text_auto='.2f',
                        title='Feature Correlation Heatmap', color_continuous_scale='RdBu_r')
        fig.update_layout(height=500)
        fig.show()

        corr_with_target = corr['ridership'].sort_values(ascending=False)
        print('Correlation with Ridership:')
        print(corr_with_target)

## 9. Key Takeaways

1. **Strong seasonal patterns** - ridership peaks during school months and dips in summer
2. **12-month lag is highly correlated** - annual cyclicality is the dominant pattern
3. **Rolling averages** smooth noise and provide strong baseline signals
4. **COVID disruption** is visible as a major anomaly in ridership trends
5. **Transit network** shows typical hub-and-spoke structure with a few high-centrality stops
6. **Lag/rolling regression** can effectively forecast without requiring Prophet or ARIMA